server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wevote?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  redis:
    host: 127.0.0.1
    port: 6379
    password: 1234
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0
  main:
    allow-bean-definition-overriding: true

pagehelper:
  supportMethodsArguments: true
  reasonable: true
  helperDialect: mysql
  params: count=countSql

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.hbgc.domain

upload:
  win:
    path: d:/uploadFiles/
  linux:
    path: /usr/share/nginx/html/test/image/